spring.application.name=Projeto3aAPI

# =======================================================
# CONFIGURAÇÕES DO POSTGRESQL (BANCO DO RENDER EXTERNO)
# =======================================================
# NOTA: Mude para a URL Interna quando for fazer o Deploy final dentro do Render
spring.datasource.url=jdbc:postgresql://dpg-d85hl8d7vvec7382m340-a.virginia-postgres.render.com/sextafeira13_db
spring.datasource.username=miguel
spring.datasource.password=m0NTylpNSS0tKGM6lwLEkp8mQoHt01HE
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =======================================================
# CONFIGURAÇÕES DO ACTUATOR
# =======================================================
# Expõe os endpoints na Web
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=Always

# Ativa as métricas e obriga o Spring a ler as propriedades "info.*"
management.endpoint.metrics.enabled=true
management.info.env.enabled=true

# Informações customizadas da aplicação (Mudei de 'Seu Nome' para 'Miguel')
info.app.name=Projeto3aAPI
info.app.description=API REST com Spring Boot e PostgreSQL
info.app.version=1.0.0
info.app.author=Miguel
info.app.ambiente=produção